[workspace]
members = [
  "iroh",
  "iroh-bitswap",
  "iroh-car",
  "iroh-rpc-client",
  "iroh-rpc-types",
  "iroh-gateway",
  "iroh-metrics",
  "iroh-p2p",
  "iroh-resolver",
  "iroh-store",
  "iroh-util",
  "stores/*"
]

[patch.crates-io]
# TODO: switch to crates.io once 0.45 is released
# libp2p = { git = "https://github.com/libp2p/rust-libp2p", branch = "master" }
# TODO: switch to master once the PR gets merged
libp2p = { git = "https://github.com/dignifiedquire/rust-libp2p", branch = "fix-dns-clone" }