[workspace]
members = [
  "iroh",
  "iroh-net",
  "iroh-bytes",
  "iroh-metrics",
]

[profile.optimized-release]
inherits = 'release'
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false

[patch.crates-io]
bao-tree = { path = "../bao-tree" }
blake3 = { git = "https://github.com/rklaehn/BLAKE3.git", branch = "more-guts" }
