[workspace]
members = [
  "iroh",
  "iroh-net",
  "iroh-bytes",
  "iroh-gossip",
  "iroh-metrics",
  "iroh-sync",
]

[profile.optimized-release]
inherits = 'release'
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false
