[workspace]
members = [
  "iroh",
  "iroh-io",
  "iroh-net",
  "iroh-bytes",
  "iroh-metrics",
]

[profile.optimized-release]
inherits = 'release'
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false

[patch.crates-io]
iroh-io = { path = "./iroh-io" }
bao-tree = { git = "https://github.com/n0-computer/bao-tree" }
