[workspace]
members = [
  "iroh",
  "iroh-bytes",
  "iroh-ffi",
  "iroh-metrics",
  "iroh-net",
  "iroh/examples/hello-world",
  "iroh/examples/collection",
]

[profile.optimized-release]
inherits = 'release'
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false

[profile.ffi]
strip = "symbols"