[workspace]
members = [
  "iroh",
  "iroh-bytes",
  "iroh-ffi",
  "iroh-metrics",
  "iroh-net",
]

[profile.optimized-release]
inherits = 'release'
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false

[profile.ffi]
inherits = 'release'
strip = "symbols"

[patch.crates-io]
# https://github.com/mullvad/system-configuration-rs/pull/42
system-configuration = { git = "https://github.com/tmpfs/system-configuration-rs", branch = "ios-hack" }