[package]
name = "iroh"
version = "0.4.1"
edition = "2021"
readme = "README.md"
description = "IPFS reimagined"
license = "MIT/Apache-2.0"
authors = ["dignifiedquire <me@dignifiedquire.com>", "n0 team"]
repository = "https://github.com/n0-computer/iroh"
default-run = "iroh"

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.65"

[dependencies]
flume = "0.10.14"
iroh-net = { path = "../iroh-net" }
iroh-bytes = { path = "../iroh-bytes" }
tokio-util = { version = "0.7", features = ["io-util", "io"] }
tokio-stream = "0.1"

# CLI
anyhow = { version = "1", features = ["backtrace"], optional = true }
clap = { version = "4", features = ["derive"], optional = true }
config = { version = "0.13.1", default-features = false, features = ["toml", "preserve_order"], optional = true }
console = { version = "0.15.5", optional = true }
derive_more = { version = "0.99.17", git = "https://github.com/JelteF/derive_more", features = ["debug", "display", "from", "try_into"], optional = true }
dirs-next = { version = "2.0.0", optional = true }
futures = { version = "0.3.25", optional = true }
hex = { version = "0.4.3", optional = true }
indicatif = { version = "0.17", features = ["tokio"], optional = true }
multibase = { version = "0.9.1", optional = true }
num_cpus = { version = "1.15.0", optional = true }
postcard = { version = "1", default-features = false, features = ["alloc", "use-std", "experimental-derive"], optional = true }
quic-rpc = { version = "0.6", default-features = false, features = ["quinn-transport", "flume-transport"], optional = true }
quinn = { version = "0.10", optional = true }
range-collections = { version = "0.4.0", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
tempfile = { version = "3.4", optional = true }
tokio = { version = "1", features = ["io-util", "rt"], optional = true }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }


[features]
default = ["cli"]
cli = ["anyhow", "clap", "config", "console", "derive_more", "dirs-next", "futures", "hex", "indicatif", "multibase", "num_cpus", "postcard", "quic-rpc", "quinn", "range-collections", "serde", "tempfile", "tokio", "tracing", "tracing-subscriber"]
metrics = ["iroh-net/metrics"]
test = []

[dev-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
blake3 = "1.3.3"
duct = "0.13.6"
nix = "0.26.2"
rand = "0.8"
regex = { version = "1.7.1", features = ["std"] }
testdir = "0.7.2"
walkdir = "2"

[[bin]]
name = "iroh"
required-features = ["cli"]

