[package]
name = "libiroh"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = "symbols"

[lib]
name="libiroh"
crate-type = ["cdylib"]

[features]
c-headers = ["safer-ffi/headers"]

[target.x86_64-apple-darwin]
rustflags=["-C", "link-arg=-mmacosx-version-min=10.7"]
strip = "symbols"

[dependencies]
safer-ffi = { version = "0.0.10", features = ["proc_macros"] }
anyhow = "1.0.69"
iroh = { path = "../" }
libc = "0.2.141"
tempfile = "3.4"
tokio = "1.25.0"
